[project]
name = "zoo-service-template"
version = "0.1.0"
description = "Zoo service template"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "boto3>=1.38.32",
    "cwltool>=3.1.20250110105449",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]
